/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IFundToken {
  export type FundMetricsStruct = {
    totalAssetValue: BigNumberish;
    sharesSupply: BigNumberish;
    lastUpdateTime: BigNumberish;
  };

  export type FundMetricsStructOutput = [
    totalAssetValue: bigint,
    sharesSupply: bigint,
    lastUpdateTime: bigint
  ] & { totalAssetValue: bigint; sharesSupply: bigint; lastUpdateTime: bigint };
}

export interface FundTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceOf"
      | "getFundMetrics"
      | "getSharePrice"
      | "invest"
      | "owner"
      | "pause"
      | "paused"
      | "redeem"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpause"
      | "updateMetrics"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Investment"
      | "MetricsUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Redemtion"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundMetrics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSharePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invest",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateMetrics",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFundMetrics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateMetrics",
    data: BytesLike
  ): Result;
}

export namespace InvestmentEvent {
  export type InputTuple = [
    investor: AddressLike,
    usdAmount: BigNumberish,
    sharesIssued: BigNumberish,
    sharePrice: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    usdAmount: bigint,
    sharesIssued: bigint,
    sharePrice: bigint
  ];
  export interface OutputObject {
    investor: string;
    usdAmount: bigint;
    sharesIssued: bigint;
    sharePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetricsUpdatedEvent {
  export type InputTuple = [
    totalAssetValue: BigNumberish,
    sharesSupply: BigNumberish,
    sharePrice: BigNumberish
  ];
  export type OutputTuple = [
    totalAssetValue: bigint,
    sharesSupply: bigint,
    sharePrice: bigint
  ];
  export interface OutputObject {
    totalAssetValue: bigint;
    sharesSupply: bigint;
    sharePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemtionEvent {
  export type InputTuple = [
    investor: AddressLike,
    shares: BigNumberish,
    usdAmount: BigNumberish,
    sharePrice: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    shares: bigint,
    usdAmount: bigint,
    sharePrice: bigint
  ];
  export interface OutputObject {
    investor: string;
    shares: bigint;
    usdAmount: bigint;
    sharePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundToken extends BaseContract {
  connect(runner?: ContractRunner | null): FundToken;
  waitForDeployment(): Promise<this>;

  interface: FundTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceOf: TypedContractMethod<[investor: AddressLike], [bigint], "view">;

  getFundMetrics: TypedContractMethod<
    [],
    [IFundToken.FundMetricsStructOutput],
    "view"
  >;

  getSharePrice: TypedContractMethod<[], [bigint], "view">;

  invest: TypedContractMethod<
    [investor: AddressLike, usdAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  redeem: TypedContractMethod<
    [investor: AddressLike, shares: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateMetrics: TypedContractMethod<
    [newTotalAssetValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFundMetrics"
  ): TypedContractMethod<[], [IFundToken.FundMetricsStructOutput], "view">;
  getFunction(
    nameOrSignature: "getSharePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "invest"
  ): TypedContractMethod<
    [investor: AddressLike, usdAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [investor: AddressLike, shares: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMetrics"
  ): TypedContractMethod<
    [newTotalAssetValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Investment"
  ): TypedContractEvent<
    InvestmentEvent.InputTuple,
    InvestmentEvent.OutputTuple,
    InvestmentEvent.OutputObject
  >;
  getEvent(
    key: "MetricsUpdated"
  ): TypedContractEvent<
    MetricsUpdatedEvent.InputTuple,
    MetricsUpdatedEvent.OutputTuple,
    MetricsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Redemtion"
  ): TypedContractEvent<
    RedemtionEvent.InputTuple,
    RedemtionEvent.OutputTuple,
    RedemtionEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Investment(address,uint256,uint256,uint256)": TypedContractEvent<
      InvestmentEvent.InputTuple,
      InvestmentEvent.OutputTuple,
      InvestmentEvent.OutputObject
    >;
    Investment: TypedContractEvent<
      InvestmentEvent.InputTuple,
      InvestmentEvent.OutputTuple,
      InvestmentEvent.OutputObject
    >;

    "MetricsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      MetricsUpdatedEvent.InputTuple,
      MetricsUpdatedEvent.OutputTuple,
      MetricsUpdatedEvent.OutputObject
    >;
    MetricsUpdated: TypedContractEvent<
      MetricsUpdatedEvent.InputTuple,
      MetricsUpdatedEvent.OutputTuple,
      MetricsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Redemtion(address,uint256,uint256,uint256)": TypedContractEvent<
      RedemtionEvent.InputTuple,
      RedemtionEvent.OutputTuple,
      RedemtionEvent.OutputObject
    >;
    Redemtion: TypedContractEvent<
      RedemtionEvent.InputTuple,
      RedemtionEvent.OutputTuple,
      RedemtionEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
