/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FundToken__factory } from "./FundToken__factory";
export { IFundToken__factory } from "./IFundToken__factory";
